# Generated by Django 5.2.10 on 2026-01-16 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "charges_hst",
                    models.BooleanField(
                        default=False,
                        help_text="Does this worker charge HST on their labor?",
                    ),
                ),
                ("is_employee", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "estimate_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, help_text="Actual hours on site", max_digits=4
                    ),
                ),
                (
                    "round_trip_kms",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("used_company_truck", models.BooleanField(default=False)),
                (
                    "worked_at_hq",
                    models.BooleanField(
                        default=False, help_text="Working at Jon's place?"
                    ),
                ),
                (
                    "materials_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Materials provided by tech from their inventory",
                        max_digits=8,
                    ),
                ),
                (
                    "receipts_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Out of pocket purchases",
                        max_digits=8,
                    ),
                ),
                (
                    "receipt_card_digits",
                    models.CharField(
                        blank=True, help_text="Last 4 digits of card used", max_length=4
                    ),
                ),
                (
                    "calculated_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="management.job"
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.worker",
                    ),
                ),
            ],
        ),
    ]
