# Generated by Django 5.2.10 on 2026-01-16 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="assigned_workers",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_jobs", to="management.worker"
            ),
        ),
        migrations.AddField(
            model_name="worker",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="charges_hst",
            field=models.BooleanField(default=False),
        ),
    ]
