# Generated by Django 5.2.10 on 2026-01-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_job_assigned_workers_worker_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="Client contact number", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(
                help_text="Detailed job description and scope of work"
            ),
        ),
    ]
