# Generated by Django 5.2.10 on 2026-01-20 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0003_client_phone_number_alter_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="hours_worked",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Actual hours on site (0.01 - 24.00)",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(
                        0.01, message="Hours worked must be greater than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        24, message="Hours worked cannot exceed 24 hours in a day"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="materials_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Materials provided by tech from their inventory",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Materials cost cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        99999.99, message="Materials cost seems unreasonably high"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="receipt_card_digits",
            field=models.CharField(
                blank=True,
                help_text="Last 4 digits of card used (numbers only)",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_card_digits",
                        message="Enter exactly 4 digits",
                        regex="^\\d{4}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="receipts_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Out of pocket purchases",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Receipts total cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        99999.99, message="Receipts total seems unreasonably high"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="round_trip_kms",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Round trip distance in kilometers",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Kilometers cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        9999.99, message="Distance seems unreasonably high"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Hourly rate in dollars (max $999.99)",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Hourly rate cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        999.99, message="Hourly rate seems unreasonably high"
                    ),
                ],
            ),
        ),
    ]
