# Generated by Django 5.2.10 on 2026-01-20 19:55

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0004_alter_timesheet_hours_worked_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTimesheet",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual hours on site (0.01 - 24.00)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, message="Hours worked must be greater than 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                24,
                                message="Hours worked cannot exceed 24 hours in a day",
                            ),
                        ],
                    ),
                ),
                (
                    "round_trip_kms",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Round trip distance in kilometers",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Kilometers cannot be negative"
                            ),
                            django.core.validators.MaxValueValidator(
                                9999.99, message="Distance seems unreasonably high"
                            ),
                        ],
                    ),
                ),
                ("used_company_truck", models.BooleanField(default=False)),
                (
                    "worked_at_hq",
                    models.BooleanField(
                        default=False, help_text="Working at Jon's place?"
                    ),
                ),
                (
                    "materials_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Materials provided by tech from their inventory",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Materials cost cannot be negative"
                            ),
                            django.core.validators.MaxValueValidator(
                                99999.99,
                                message="Materials cost seems unreasonably high",
                            ),
                        ],
                    ),
                ),
                (
                    "receipts_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Out of pocket purchases",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Receipts total cannot be negative"
                            ),
                            django.core.validators.MaxValueValidator(
                                99999.99,
                                message="Receipts total seems unreasonably high",
                            ),
                        ],
                    ),
                ),
                (
                    "receipt_card_digits",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits of card used (numbers only)",
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_card_digits",
                                message="Enter exactly 4 digits",
                                regex="^\\d{4}$",
                            )
                        ],
                    ),
                ),
                (
                    "calculated_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="management.job",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="management.worker",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical timesheet",
                "verbose_name_plural": "historical timesheets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWorker",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly rate in dollars (max $999.99)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Hourly rate cannot be negative"
                            ),
                            django.core.validators.MaxValueValidator(
                                999.99, message="Hourly rate seems unreasonably high"
                            ),
                        ],
                    ),
                ),
                ("charges_hst", models.BooleanField(default=False)),
                ("is_employee", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical worker",
                "verbose_name_plural": "historical workers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
