# Generated by Django 5.2.10 on 2026-01-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_historicaltimesheet_historicalworker"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="estimated_duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated hours to complete",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="scheduled_date",
            field=models.DateField(
                blank=True, help_text="When the job is scheduled", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="scheduled_time",
            field=models.TimeField(
                blank=True, help_text="Start time for the job", null=True
            ),
        ),
    ]
