# Generated by Django 5.2.10 on 2026-01-22 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_job_estimated_duration_job_scheduled_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltimesheet",
            name="materials_cost",
        ),
        migrations.RemoveField(
            model_name="timesheet",
            name="materials_cost",
        ),
        migrations.AddField(
            model_name="historicaltimesheet",
            name="company_materials",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Materials purchased with company card/account",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Amount cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        99999.99, message="Amount seems unreasonably high"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicaltimesheet",
            name="personal_materials",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Materials purchased with personal funds (will be reimbursed)",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Amount cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        99999.99, message="Amount seems unreasonably high"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="company_materials",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Materials purchased with company card/account",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Amount cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        99999.99, message="Amount seems unreasonably high"
                    ),
                ],
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="personal_materials",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Materials purchased with personal funds (will be reimbursed)",
                max_digits=8,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Amount cannot be negative"
                    ),
                    django.core.validators.MaxValueValidator(
                        99999.99, message="Amount seems unreasonably high"
                    ),
                ],
            ),
        ),
    ]
