# Generated by Django 5.2.10 on 2026-01-22 05:49

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0008_add_invoice_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=management.models.receipt_upload_path),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description of the receipt",
                        max_length=200,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount on receipt (optional)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "timesheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="management.timesheet",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
